import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/redux/redux-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }): ReactNode => (
  <html lang="en">
    <body className={inter.className}>
      <ReduxProvider>{children}</ReduxProvider>
    </body>
  </html>
);

export default RootLayout;
